#ifndef WEB_UI_ASSETS_H
#define WEB_UI_ASSETS_H

static const char INDEX_HTML[] = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n"
"    <title>PS5 LiveContainer Dashboard</title>\n"
"    <style>\n"
"        :root {\n"
"            --bg: #0b0e14;\n"
"            --card-bg: rgba(22, 27, 34, 0.85);\n"
"            --accent: #38bdf8;\n"
"            --accent-glow: rgba(56, 189, 248, 0.3);\n"
"            --success: #10b981;\n"
"            --danger: #ef4444;\n"
"            --warning: #f59e0b;\n"
"            --text: #f3f4f6;\n"
"            --text-muted: #9ca3af;\n"
"            --border: rgba(255, 255, 255, 0.1);\n"
"        }\n"
"        * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }\n"
"        body { background: var(--bg); color: var(--text); padding: 16px; min-height: 100vh; background-image: radial-gradient(circle at 50% 0%, #1e293b 0%, #0b0e14 70%); }\n"
"        header { display: flex; justify-content: space-between; align-items: center; padding-bottom: 16px; border-bottom: 1px solid var(--border); margin-bottom: 20px; }\n"
"        .logo { font-size: 1.4rem; font-weight: 700; background: linear-gradient(135deg, #38bdf8, #818cf8); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }\n"
"        .badge { font-size: 0.75rem; padding: 4px 8px; border-radius: 9999px; font-weight: 600; text-transform: uppercase; }\n"
"        .badge-running { background: rgba(16, 185, 129, 0.2); color: var(--success); border: 1px solid var(--success); }\n"
"        .badge-idle { background: rgba(156, 163, 175, 0.2); color: var(--text-muted); border: 1px solid var(--text-muted); }\n"
"        .badge-crashed { background: rgba(239, 68, 68, 0.2); color: var(--danger); border: 1px solid var(--danger); }\n"
"        .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 16px; margin-bottom: 24px; }\n"
"        .card { background: var(--card-bg); border: 1px solid var(--border); border-radius: 14px; padding: 16px; backdrop-filter: blur(10px); box-shadow: 0 4px 20px rgba(0,0,0,0.3); transition: transform 0.2s; }\n"
"        .card:hover { transform: translateY(-2px); }\n"
"        .card-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; }\n"
"        .card-title { font-size: 1.1rem; font-weight: 600; }\n"
"        .card-desc { font-size: 0.85rem; color: var(--text-muted); margin-bottom: 16px; height: 38px; overflow: hidden; }\n"
"        .card-actions { display: flex; gap: 8px; }\n"
"        .btn { flex: 1; padding: 10px; border: none; border-radius: 8px; font-weight: 600; cursor: pointer; transition: all 0.2s; font-size: 0.9rem; }\n"
"        .btn-launch { background: linear-gradient(135deg, #0284c7, #0369a1); color: white; box-shadow: 0 0 12px var(--accent-glow); }\n"
"        .btn-launch:active { transform: scale(0.98); }\n"
"        .btn-stop { background: var(--danger); color: white; }\n"
"        .upload-section { background: var(--card-bg); border: 2px dashed var(--border); border-radius: 14px; padding: 24px; text-align: center; margin-bottom: 24px; cursor: pointer; }\n"
"        .upload-section:hover { border-color: var(--accent); }\n"
"        .console-box { background: #000; border: 1px solid var(--border); border-radius: 10px; padding: 12px; font-family: monospace; font-size: 0.8rem; height: 180px; overflow-y: auto; color: #38bdf8; white-space: pre-wrap; }\n"
"        .footer { text-align: center; color: var(--text-muted); font-size: 0.8rem; margin-top: 24px; }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <header>\n"
"        <div>\n"
"            <div class=\"logo\">PS5 LiveContainer</div>\n"
"            <small style=\"color: var(--text-muted);\">In-Memory ELF Sandbox & Runner</small>\n"
"        </div>\n"
"        <div id=\"global-status\" class=\"badge badge-running\">System Ready</div>\n"
"    </header>\n"
"\n"
"    <div class=\"upload-section\" onclick=\"document.getElementById('file-input').click()\">\n"
"        <input type=\"file\" id=\"file-input\" style=\"display:none;\" accept=\".elf\" onchange=\"uploadPayload(this.files[0])\">\n"
"        <p style=\"font-weight: 600; font-size: 1rem; margin-bottom: 4px;\">Drop or Tap to Upload .ELF Payload</p>\n"
"        <small style=\"color: var(--text-muted);\">Instantly launches into isolated LiveContainer sandbox</small>\n"
"    </div>\n"
"\n"
"    <h3 style=\"margin-bottom: 12px; font-size: 1rem; color: var(--text-muted); text-transform: uppercase; letter-spacing: 1px;\">Container Slots</h3>\n"
"    <div id=\"containers-grid\" class=\"grid\">Loading containers...</div>\n"
"\n"
"    <h3 style=\"margin-bottom: 12px; font-size: 1rem; color: var(--text-muted); text-transform: uppercase; letter-spacing: 1px;\">Live Console Log</h3>\n"
"    <div id=\"console-log\" class=\"console-box\">Connecting to PS5 LiveContainer daemon...\n</div>\n"
"\n"
"    <div class=\"footer\">PS5 LiveContainer Framework &bull; Port 8080</div>\n"
"\n"
"    <script>\n"
"        async function refreshData() {\n"
"            try {\n"
"                const res = await fetch('/api/containers');\n"
"                const data = await res.json();\n"
"                renderContainers(data.slots);\n"
"                \n"
"                const logRes = await fetch('/api/logs');\n"
"                const logData = await logRes.text();\n"
"                const box = document.getElementById('console-log');\n"
"                box.textContent = logData;\n"
"                box.scrollTop = box.scrollHeight;\n"
"            } catch(e) { console.error(e); }\n"
"        }\n"
"        \n"
"        function renderContainers(slots) {\n"
"            const grid = document.getElementById('containers-grid');\n"
"            if (!slots || slots.length === 0) {\n"
"                grid.innerHTML = '<p style=\"color: var(--text-muted);\">No containers installed. Upload an .elf above.</p>';\n"
"                return;\n"
"            }\n"
"            grid.innerHTML = slots.map(s => `\n"
"                <div class=\"card\">\n"
"                    <div class=\"card-header\">\n"
"                        <div class=\"card-title\">${s.name}</div>\n"
"                        <span class=\"badge badge-${s.state.toLowerCase()}\">${s.state}</span>\n"
"                    </div>\n"
"                    <div class=\"card-desc\">${s.description || 'Native PS5 Homebrew Container'}</div>\n"
"                    <div class=\"card-actions\">\n"
"                        ${s.state === 'RUNNING' \n"
"                            ? `<button class=\"btn btn-stop\" onclick=\"stopContainer('${s.id}')\">Stop</button>`\n"
"                            : `<button class=\"btn btn-launch\" onclick=\"launchContainer('${s.id}')\">Launch</button>`\n"
"                        }\n"
"                    </div>\n"
"                </div>\n"
"            `).join('');\n"
"        }\n"
"\n"
"        async function launchContainer(id) {\n"
"            await fetch('/api/launch?id=' + encodeURIComponent(id), { method: 'POST' });\n"
"            setTimeout(refreshData, 500);\n"
"        }\n"
"\n"
"        async function stopContainer(id) {\n"
"            await fetch('/api/stop?id=' + encodeURIComponent(id), { method: 'POST' });\n"
"            setTimeout(refreshData, 500);\n"
"        }\n"
"\n"
"        async function uploadPayload(file) {\n"
"            if (!file) return;\n"
"            const formData = new FormData();\n"
"            formData.append('payload', file);\n"
"            const box = document.getElementById('console-log');\n"
"            box.textContent += '\\n[LiveContainer] Uploading ' + file.name + '...';\n"
"            await fetch('/api/upload', { method: 'POST', body: formData });\n"
"            setTimeout(refreshData, 800);\n"
"        }\n"
"\n"
"        setInterval(refreshData, 2000);\n"
"        refreshData();\n"
"    </script>\n"
"</body>\n"
"</html>\n";

#endif /* WEB_UI_ASSETS_H */
